micronaut:
  application:
    name: becommerceBff
  server:
    context-path: /api/becommerce/v1
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

netty:
  default:
    allocator:
      max-order: 3
