micronaut:
  application:
    name: becommerceBff
  server:
    context-path: /api/becommerce/v1

endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

netty:
  default:
    allocator:
      max-order: 3
