micronaut:
  application:
    name: becommerceBff
  server:
    context-path: /api/becommerce/v1

endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: ${JDBC_URL}
    driverClassName: ${JDBC_DRIVER}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    maxActive: 3
    maxIdle: 3
    initialSize: 1

jpa:
  default:
    entity-scan:
      packages: 'com.becommerce.model'
    properties:
      hibernate:
        show_sql: false

JWT_SECRET_KEY: ${JWT_SECRET_KEY}
JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}

S3_ACCESS_KEY: ${S3_ACCESS_KEY}
S3_SECRET_KEY: ${S3_SECRET_KEY}
S3_BUCKET_NAME: ${S3_BUCKET_NAME}
S3_REGION: ${S3_REGION}