micronaut:
  application:
    name: becommerceBff
  server:
    context-path: /api/becommerce/v1

endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/BeCommerce
    driverClassName: org.postgresql.Driver
    username: root
    password: root
    maxActive: 3
    maxIdle: 3
    initialSize: 1

jpa:
  default:
    entity-scan:
      packages: 'com.becommerce.model'
    properties:
      hibernate:
        show_sql: false