micronaut:
  application:
    name: becommerceBff
  server:
    context-path: /api/becommerce/v1

endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: ${JDBC_URL}
    driverClassName: ${JDBC_DRIVER}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    maxActive: 3
    maxIdle: 3
    initialSize: 1

jpa:
  default:
    entity-scan:
      packages: 'com.becommerce.model'
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: drop-and-create
              create-target: createFile.ddl
              drop-target: dropFile.ddl
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

JWT_SECRET_KEY: ${JWT_SECRET_KEY}
JWT_EXPIRATION_TIME: 15