micronaut:
  application:
    name: becommerceBff
  server:
    context-path: /api/becommerce/v1

endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/BeCommerce}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:root}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
    schema-generate: CREATE_DROP

jpa:
  default:
    entity-scan:
      packages: 'com.becommerce.model'
    properties:
      hibernate:
        show_sql: false